name: Schedule Notifications

on:
  schedule:
    - cron: '30 0 * * *' # Runs at 5:30 AM IST (midnight UTC + 5:30)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Display environment variables for debugging
        run: |
          echo "DB_HOST: ${DB_HOST}"
          echo "DB_USER: ${DB_USER}"
          echo "DB_PASSWORD: ${DB_PASSWORD}"
          echo "DB_DATABASE: ${DB_DATABASE}"
          echo "ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}"
          echo "ONESIGNAL_API_KEY: ${ONESIGNAL_API_KEY}"
          echo "ONESIGNAL_ANDROID_CHANNEL_ID: ${ONESIGNAL_ANDROID_CHANNEL_ID}"
       

      - name: Run notification script
        run: npm start
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
          ONESIGNAL_ANDROID_CHANNEL_ID: ${{ secrets.ONESIGNAL_ANDROID_CHANNEL_ID }}
